-- Seed guests from guests.txt
-- login_slug = lowercase full name without spaces (e.g. Gustaf Tadaa → gustaftadaa)
-- Idempotent: upsert on login_slug.

insert into guests (real_name, login_slug) values
  ('Malin Tadaa', 'malintadaa'),
  ('Gustaf Tadaa', 'gustaftadaa'),
  ('Jesper Lejfjord', 'jesperlejfjord'),
  ('Elina Melakoski', 'elinamelakoski'),
  ('Li Tadaa', 'litadaa'),
  ('Adam Heindorf', 'adamheindorf'),
  ('Louise von Bahr', 'louisevonbahr'),
  ('Mattis Norrvidd', 'mattisnorrvidd'),
  ('Evelina Andersson', 'evelinaandersson'),
  ('Amanda Mungsgård', 'amandamungsgard'),
  ('Viktor Ansund', 'viktoransund'),
  ('Josefin Ansund', 'josefinansund'),
  ('Johanna Bergman', 'johannabergman'),
  ('Erik Bergman', 'erikbergman'),
  ('Jesper Lindmarker', 'jesperlindmarker'),
  ('Josefin Löwing', 'josefinlowing'),
  ('Navid Modiri', 'navidmodiri'),
  ('Linnea Appert', 'linneaappert'),
  ('Hampus Lindblad', 'hampuslindblad'),
  ('Linnea Ekbom', 'linneaekbom'),
  ('Gustav Lund', 'gustavlund'),
  ('Amalia Wahlström', 'amaliawahlstrom'),
  ('Fabian Macklin', 'fabianmacklin'),
  ('Mini Macklin', 'minimacklin'),
  ('Petter Wallberg', 'petterwallberg'),
  ('Elin Mårtensson', 'elinmartensson'),
  ('Ludvig von Bahr', 'ludvigvonbahr'),
  ('Minerva Löwgren', 'minervalowgren'),
  ('Alexandra Palmquist', 'alexandrapalmquist'),
  ('Olle Bjerkås', 'ollebjerkas'),
  ('Ulrika Hammar', 'ulrikahammar'),
  ('Edvin Thungren', 'edvinthungren'),
  ('Martina Hessel', 'martinahessel'),
  ('Chris Kummelstedt', 'chriskummelstedt')
on conflict (login_slug) do update set real_name = excluded.real_name;
